language: node_js
node_js: "5.11"
notifications:
  email: false
  slack: 
    on_success: always
before_install:
  - chmod a+x ./scripts/start.sh
  - chmod a+x ./scripts/install.sh
script:
  - scripts/start.sh
  - scripts/install.sh
deploy:
  provider: s3
  access_key_id: ${S3_ACCESS_KEY}
  secret_access_key: ${S3_SECRET_ACCESS_KEY}
  bucket: "service-platform-hml"
  skip_cleanup: true

after_success:
  # after deploy in s3
branches:
  except:
    - master
